### ISSUE TITLE
error runninig initial npm i

### ISSUE THREAD

**Issue by Geraldf** [valor-software/angular2-quickstart#17]
Hi 
when i clone this repo, and run npm i I do get the following error. 

npm ERR! ng2-bootstrap@1.0.4 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ng2-bootstrap@1.0.4 postinstall script 'typings install'.
npm ERR! This is most likely a problem with the ng2-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get their info via:
npm ERR!     npm owner ls ng2-bootstrap
npm ERR! There is likely additional logging output above.

does anyone know how to fix it?

Gerald

**Comment by valorkin** [comment]
Pull latest, and check that you are using npm 3

**Comment by Geraldf** [comment]
Hi, that worked. great thanks

**Comment by valorkin** [comment]
awesome :)

**Comment by nsuhanshetty** [comment]
Had to replace 
"postinstall": " ./node_modules/.bin/typings install", 
with 
"postinstall": " .\\node_modules\\.bin\\typings install", 
to work for me.. 
I have a windows environment.
