### ISSUE TITLE
Moment is not a function

### ISSUE THREAD

**Issue by manuelCorredor** [valor-software/angular2-quickstart#25]
Hi, Iḿ having a lot of trouble with moment js, I have already installed moment js as a dependency and installed the typings too (ambient and dev). 

My code works fine (I'm not using the datepicker component), but sadly I get the next error:

TypeError: moment is not a function at DateFormatter.format

I've already read and follow the instructions in the main page and also in:

http://stackoverflow.com/questions/35166168/how-to-use-moment-js-library-in-angular-2-typescript-app

my system.js config look like this :

  System.config({
        transpiler: 'typescript',
        typescriptOptions: { emitDecoratorMetadata: true },
        packages: {
            "app": {
               "defaultExtension": "ts"
            },
            "node_modules/ng2-bootstrap": {
               "defaultExtension": "ts"
            },
         },
         map: {
           moment: 'node_modules/moment/moment.js'
        },
        paths: {
          "ng2-bootstrap/ng2-bootstrap":   "node_modules/ng2-bootstrap/ng2-bootstrap"
        }
      });

can you help me ?

**Comment by flyingsky** [comment]
map.moment should be "node_modules/ng2-bootstrap/node_modules/moment/moment.js" if you don't add moment into your package.json and install it.

**Comment by flyingsky** [comment]
BTW: it's not good to add moment.js as dependency, hope one day ng2-bootstrap can remove it.

**Comment by valorkin** [comment]
@flyingsky I would say, I am counting days before I will drop this 3rd party dependency!

**Comment by valorkin** [comment]
no such problem anymore
