### ISSUE TITLE
typings post install fails in windows

### ISSUE THREAD

**Issue by arcee123** [valor-software/angular2-quickstart#61]
Greetings, 
when compiling in a windows format, the postinstall script for typings fails; most likely due to a folder management issue between linux and windows.  

Error response:

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 postinstall: ` ./node_modules/bin/typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-quickstart@1.0.0 postinstall script ' ./node_modules/bin/typings install'.
npm ERR! This is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!      ./node_modules/bin/typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\evan.cutler\Documents\node projects\angular2-quickstart-master\npm-debug.log

If dependancies are installed manually, site does work.
Thanks much for a great start point.  It gives us beginners a great place to start with.

**Comment by valorkin** [comment]
Problem is I am not using windows
So I will appreciate any help with this issue

**Comment by arcee123** [comment]
I forked your code and made two pull requests to assist with windows deployments.
i recommend trying to run them on your system to make sure you are still good.

**Comment by valorkin** [comment]
Thanks I will it
