### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by PEsteves8** [valor-software/angular2-quickstart#73]
Hi,

All angular related modules, including ng2-bootstrap aren't found. 
Chrome's console just logs 404's all over the place.
I installed everything properly and am using Windows 10

Thanks

**Comment by jfpicard123** [comment]
Same here ..

**Comment by matt-slater** [comment]
same here....

**Comment by valorkin** [comment]
hm, should be fixed
if not find me here:
https://www.hamsterpad.com/chat/ng2
