### ISSUE TITLE
Cannot be installed: npm ERR! code EPEERINVALID 

### ISSUE THREAD

**Issue by Toadskin** [valor-software/angular2-quickstart#80]
Had this problem with a couple of other packages where you cannot get past square one (install) and there's no hint of a solution short of forking and fixing package references I suppose. 

I'm using angular 2.0.0-rc4 

npm WARN peerDependencies The peer dependency @angular/router@3.0.0-beta.2 included from ng2-bootstrap will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ng2-bootstrap@latest" "--save"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/router@3.0.0-beta.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer ng2-bootstrap@1.0.18 wants @angular/router@3.0.0-beta.2

**Comment by valorkin** [comment]
hey
1. use npm 3
2. just install missing dependecy

3. it is an issue that router is peer dependency of ng2-bootstrap

**Comment by valorkin** [comment]
fixed\published
