### ISSUE TITLE
error TS2304: Cannot find name 'Promise'.

### ISSUE THREAD

**Issue by manunoly** [valor-software/angular2-quickstart#84]
[npm-debug.log.zip](https://github.com/valor-software/angular2-quickstart/files/361812/npm-debug.log.zip)

**Comment by manunoly** [comment]
i was able to fix running this command
typings install dt~es6-promise dt~es6-collections --global --save

more detail here
http://stackoverflow.com/questions/33332394/angular-2-typescript-cant-find-names

 Thanks

**Comment by valorkin** [comment]
you could just run `typings install`

**Comment by valorkin** [comment]
BTW when typescript will be released we will forget about this issues!
